"""
plot_cross_site_v2.py

Regenerates fig_cross_site from the CORRECT Phase 3 dataset
(results/phase3/master_summary.csv), replacing the stale Phase 2 version
that was generated by the archived plot_chapter7.py from
results/archive/phase2_legacy/all_results_final.csv (n=3 seeds).

Confirmed stale: the old fig_cross_site.png's numbers (site10: 327/365,
site5: 650/728, site2: 0/10) match all_results_final.csv exactly, not
master_summary.csv.
"""
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

MASTER_CSV = "results/phase3/master_summary.csv"
CLASS_CSV = "data/processed/site_classification.csv"
OUT_DIR = "results/figures"

df = pd.read_csv(MASTER_CSV)
cls = pd.read_csv(CLASS_CSV).set_index("site")["difficulty"].to_dict()

sub = df[df.lead_scenario == "normal"]
piv = sub.groupby(["site", "policy"])["EENS_kWh"].mean().unstack()[["rlinv", "b1"]]

# order sites the same way the original figure did: site1..site10
site_order = [f"site{i}" for i in range(1, 11)]
piv = piv.reindex(site_order)

COLOR = {"Easy": "#4dac26", "Medium": "#d9a441", "Hard": "#d6604d"}

fig, ax = plt.subplots(figsize=(13, 6))
x = np.arange(len(site_order))
w = 0.38
b1 = ax.bar(x - w/2, piv["rlinv"], w, color="#2166ac", label="RLInv (proposed)")
b2 = ax.bar(x + w/2, piv["b1"], w, color="#4dac26", label="B1 (best baseline)")

ax.set_xticks(x)
labels = ax.set_xticklabels(site_order, fontweight="bold")
for lbl, site in zip(labels, site_order):
    lbl.set_color(COLOR.get(cls.get(site, "Medium"), "black"))

ax.set_ylabel("Mean EENS (kWh / episode)")
ax.set_title("Cross-Site Robustness: RLInv vs B1 (normal logistics)\n"
             "X-axis colour: green=Easy, orange=Medium, red=Hard",
             fontsize=13, fontweight="bold")
ax.legend(fontsize=11)

for b, vals in [(b1, piv["rlinv"]), (b2, piv["b1"])]:
    for rect, v in zip(b, vals):
        if v > 0.005:
            ax.text(rect.get_x() + rect.get_width()/2, rect.get_height(),
                    f"{v:.2f}", ha="center", va="bottom", fontsize=9, fontweight="bold")

plt.tight_layout()
plt.savefig(f"{OUT_DIR}/fig_cross_site_v2.png", dpi=200, bbox_inches="tight")
plt.close()
print("Saved fig_cross_site_v2.png")
print(piv.round(2))
